#!/bin/sh
eval $(bch.mnt.scan)
export_ () { export $1=$2 ; }
export_ WS852_DST           ${DEVICE_PUMPKIN_WS852_DST}
export_ WS852_UPLOAD_DIR    ${DEVICE_PUMPKIN_WS852_DST}
export_ WS852_DEVICE_ROOT   ${DEVICE_Olympus_WS852_ROOT}

${BCH_APP_WS852}/scripts/ws852.py $*
